[project]
name = "rampid-detector"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "duckduckgo-search>=8.1.1",
    "gitpython>=3.1.51",
    "playwright>=1.61.0",
    "requests>=2.34.2",
    "streamlit>=1.59.2",
]
